name: hopper_sim
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.11
  - ipykernel
  - pyyaml
  - numpy
  - scipy
  - matplotlib
  - cyipopt
prefix: /opt/anaconda3/envs/hopper_sim
